<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="4"
           failures="2"
           errors="0"
           skipped="0"
           time="1.018">
  <properties />
            <testcase name="addOrg" time="0.081" classname="beansRef.Demo">
                <failure type="org.mongodb.morphia.mapping.validation.ConstraintViolationException"
                  message="Number of violations: 1 
NoId complained about beansRef.OrgBean. : No field is annotated with @Id; but it is required"
              >
<![CDATA[org.mongodb.morphia.mapping.validation.ConstraintViolationException: Number of violations: 1 
NoId complained about beansRef.OrgBean. : No field is annotated with @Id; but it is required
  org.mongodb.morphia.mapping.validation.MappingValidator.validate(MappingValidator.java:65)
  org.mongodb.morphia.mapping.validation.MappingValidator.validate(MappingValidator.java:175)
  org.mongodb.morphia.mapping.MappedClass.validate(MappedClass.java:355)
  org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:173)
  org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:161)
  org.mongodb.morphia.Morphia.map(Morphia.java:67)
  beansRef.OrgBean.writer(OrgBean.java:51)
  beansRef.Demo.addOrg(Demo.java:15)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
            <testcase name="addAccount" time="0.918" classname="beansRef.Demo">
                <failure type="com.mongodb.MongoException$DuplicateKey"
                  message="{ &quot;serverUsed&quot; : &quot;127.0.0.1:27017&quot; , &quot;ok&quot; : 1 , &quot;n&quot; : 0 , &quot;err&quot; : &quot;E11000 duplicate key error index: test.AccountBean.$account_1 dup key: { : \&quot;account-first\&quot; }&quot; , &quot;code&quot; : 11000}"
              >
<![CDATA[com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "127.0.0.1:27017" , "ok" : 1 , "n" : 0 , "err" : "E11000 duplicate key error index: test.AccountBean.$account_1 dup key: { : \"account-first\" }" , "code" : 11000}
  com.mongodb.CommandResult.getWriteException(CommandResult.java:88)
  com.mongodb.CommandResult.getException(CommandResult.java:79)
  com.mongodb.DBCollectionImpl.translateBulkWriteException(DBCollectionImpl.java:316)
  com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:191)
  com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:167)
  com.mongodb.DBCollection.insert(DBCollection.java:161)
  com.mongodb.DBCollection.insert(DBCollection.java:107)
  com.mongodb.DBCollection.save(DBCollection.java:1049)
  org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1027)
  org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1096)
  org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1079)
  beansRef.AccountBean.writer(AccountBean.java:61)
  beansRef.Demo.addAccount(Demo.java:31)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="readAccount" time="0.018" classname="beansRef.Demo" />
                <testcase name="readOrg" time="0.001" classname="beansRef.Demo" />
      
</testsuite>
